# Production Environment Configuration

# Data settings
DATA_DIR: "/data/raw"
PROCESSED_DATA_DIR: "/data/processed"
DATASET_NAME: "imdb_reviews"

# Model settings
MODEL_NAME: "distilbert-base-uncased"
MAX_SEQ_LENGTH: 512
BATCH_SIZE: 32
EPOCHS: 5
LEARNING_RATE: 2e-5

# Training settings
SAVE_CHECKPOINTS: true
CHECKPOINT_DIR: "/models/checkpoints"
LOG_DIR: "/var/log/text_classification"

# Experiment tracking
MLFLOW_TRACKING_URI: "http://mlflow-server:5000"
EXPERIMENT_NAME: "text_classification_prod"